services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: Bazarr
    environment:
      - PUID=1125
      - PGID=1250
      - TZ=America/Toronto
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config:rw
      - /share/Media:/data:rw
    networks:
      - arr-net
    ports:
      - 16767:6767
    restart: unless-stopped

networks:
  arr-net:
    external: true
