services:
  gluetun:
    extends:
      file: &base ../common/gluetor/gluetor-base.yaml
      service: gluetun
    container_name: gluetor-int-gluetun
    networks:
      - arr-net

  qbt:
    extends:
      file: *base
      service: qbt
    container_name: gluetor-int-qbt

networks:
  arr-net:
    external: true
