services:
  gluetun:
    extends:
      file: &base ../common/gluetor/gluetor-base.yaml
      service: gluetun
    container_name: gluetor-ext-gluetun
    ports:
      - ${WEBUI_PORT:-8080}:${WEBUI_PORT:-8080}

  qbt:
    extends:
      file: *base
      service: qbt
    container_name: gluetor-ext-qbt
